/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BitcoinSPV {
  export type BlockHeaderStruct = {
    version: BigNumberish;
    prevHash: BytesLike;
    merkleRoot: BytesLike;
    timestamp: BigNumberish;
    bits: BigNumberish;
    nonce: BigNumberish;
  };

  export type BlockHeaderStructOutput = [
    version: bigint,
    prevHash: string,
    merkleRoot: string,
    timestamp: bigint,
    bits: bigint,
    nonce: bigint
  ] & {
    version: bigint;
    prevHash: string;
    merkleRoot: string;
    timestamp: bigint;
    bits: bigint;
    nonce: bigint;
  };
}

export interface BitcoinSPVInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPoW"
      | "hash256"
      | "knownHeaders"
      | "parseHeader"
      | "submitHeader"
      | "verifyTxInclusion"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HeaderSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkPoW",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hash256", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "knownHeaders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "parseHeader",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitHeader",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTxInclusion",
    values: [BytesLike, BytesLike, BytesLike[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "checkPoW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hash256", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "knownHeaders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseHeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitHeader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTxInclusion",
    data: BytesLike
  ): Result;
}

export namespace HeaderSubmittedEvent {
  export type InputTuple = [blockHash: BytesLike];
  export type OutputTuple = [blockHash: string];
  export interface OutputObject {
    blockHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BitcoinSPV extends BaseContract {
  connect(runner?: ContractRunner | null): BitcoinSPV;
  waitForDeployment(): Promise<this>;

  interface: BitcoinSPVInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPoW: TypedContractMethod<
    [header: BytesLike, simplifiedTarget: BigNumberish],
    [boolean],
    "view"
  >;

  hash256: TypedContractMethod<[data: BytesLike], [string], "view">;

  knownHeaders: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  parseHeader: TypedContractMethod<
    [header: BytesLike],
    [BitcoinSPV.BlockHeaderStructOutput],
    "view"
  >;

  submitHeader: TypedContractMethod<
    [header: BytesLike, simplifiedTarget: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyTxInclusion: TypedContractMethod<
    [
      txid: BytesLike,
      merkleRoot: BytesLike,
      proof: BytesLike[],
      index: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPoW"
  ): TypedContractMethod<
    [header: BytesLike, simplifiedTarget: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash256"
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "knownHeaders"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "parseHeader"
  ): TypedContractMethod<
    [header: BytesLike],
    [BitcoinSPV.BlockHeaderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitHeader"
  ): TypedContractMethod<
    [header: BytesLike, simplifiedTarget: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyTxInclusion"
  ): TypedContractMethod<
    [
      txid: BytesLike,
      merkleRoot: BytesLike,
      proof: BytesLike[],
      index: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "HeaderSubmitted"
  ): TypedContractEvent<
    HeaderSubmittedEvent.InputTuple,
    HeaderSubmittedEvent.OutputTuple,
    HeaderSubmittedEvent.OutputObject
  >;

  filters: {
    "HeaderSubmitted(bytes32)": TypedContractEvent<
      HeaderSubmittedEvent.InputTuple,
      HeaderSubmittedEvent.OutputTuple,
      HeaderSubmittedEvent.OutputObject
    >;
    HeaderSubmitted: TypedContractEvent<
      HeaderSubmittedEvent.InputTuple,
      HeaderSubmittedEvent.OutputTuple,
      HeaderSubmittedEvent.OutputObject
    >;
  };
}
